main: de.haeherfeder.plug.Main.Main
name: Chest_Towny
version: 0.0.1
description: This plugin does so much stuff it can't be contained!
website: haeherfeder.de
permissions:
    Chestshop.CreateOutsideShops:
        description: Test
depend: [ChestShop, Towny]
